# Use the official ASP.NET Core runtime image as the base image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Use the .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Copy the project file from the BulkyWeb folder
COPY Bulky_MVC/BulkyWeb/FashionFindsWeb.csproj BulkyWeb/
RUN dotnet restore BulkyWeb/FashionFindsWeb.csproj

# Copy the entire source code from the BulkyWeb folder
COPY . .
WORKDIR /src/BulkyWeb
RUN dotnet build FashionFindsWeb.csproj -c Release -o /app/build

# Publish the app
FROM build AS publish
RUN dotnet publish FashionFindsWeb.csproj -c Release -o /app/publish

# Final image to run the app
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FashionFindsWeb.dll"]
